server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  storage:
    skill-file: skills.json
    soll-file: soll.json
  csv:
    separator: ;
